
export const EVENTS = 'Events';
export const NEWS = 'News';
export const BLOGS = 'Blogs';
export const SHOW = 'Anzeigen';
export const Hide = 'Ausblenden';
export const COLOR_TOOLTIP = 'Entscheide welche Farbe genutzt werden soll. Die Standard Farbe ist: ';
export const DATE_TOOLTIP = 'Entscheide wie das Datum angezeigt werden soll';
export const DATE_FORMAT_SELECT = 'Format auswähl';
export const DEFAULT_HEADLINE = 'Überschrift';
export const DEFAULT_DESCRIPTION = 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.'
export const DEFAULT_IMAGES = ['https://tsimg.cloud/67750-26247/44a4a21d402f677068d1aaf60c708f72b663441b.jpg', 'https://tsimg.cloud/67750-26247/cdccfa04ad6699411fca8413cff3bb97f0ec9377.jpg', 'https://tsimg.cloud/67750-26247/99bc96ecc3e5d1f0f25d68931708ae82ae4e1241.jpg', 'https://tsimg.cloud/67750-26247/ff3aff7c98addb25e1de795d1d971338fb0805cf.jpg'];
export const SOURCE_CHAYNS = 'chayns';
export const SOURCE_FACEBOOK = 'Facebook';
export const SOURCE_TWITTER = 'Twitter';
export const SOURCE_YOUTUBE = 'YouTube';
export const SOURCE_FACEBOOK_PROFIL = 'Facebook-Profil';
export const SOURCE_INSTAGRAM = 'Instagram';
export const SOURCE = 'Quellen';
export const SETTINGS_EDITOR_DATE = 'Datumsformat';
export const SETTINGS_EDITOR_COLOR = 'Farbe';
